language: java

branches:
  only:
    - master
    - develop

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE mads_test;'

script: ./mvnw -DargLine="-Dspring.profiles.active=mysql" test